version: '3.9'
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: llm_tutor
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: ..
      dockerfile: infra/docker/backend.Dockerfile
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/llm_tutor
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=change_me
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    restart: unless-stopped

  worker:
    build:
      context: ..
      dockerfile: infra/docker/worker.Dockerfile
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/llm_tutor
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=change_me
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ..
      dockerfile: infra/docker/frontend.Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:5173"
    restart: unless-stopped

volumes:
  db_data: {}
